### ISSUE TITLE
Swap save file to .json format

### ISSUE THREAD

**Issue by func-vehicle** [func-vehicle/gtablocker#1]
Save files are in .bin format (reused code). It would make more sense if they were in .json format.

**Comment by bmwdeejay** [comment]
any update on this ? i would like to make a website that my friends can goto and update there ip address and i think json file would help..

**Comment by func-vehicle** [comment]
I've started working on implementing this.

**Comment by bmwdeejay** [comment]
awesome thank you <3

**Comment by func-vehicle** [comment]
Added in 37a214f42d7cc35885814973d234a5a0cde93ba9 (v2.3.0)
